### ISSUE TITLE
App sync error until files app gets unlocked

### ISSUE THREAD

**Issue by xxKeith20xx** [stefan-niedermann/nextcloud-notes#653]
When I open the Notes app and it attempts to sync, sometimes it never finishes and just shows the circular refresh animation indefinitely. I can sync if I open the Nextcloud app first, ensure it's logged in (using biometric authentication) and then open the notes app. It seems to work until the Nextcloud app gets killed at some point during the day:

```
  114 12-27 07:04:53.493  2145  2185 E AndroidRuntime: FATAL EXCEPTION: AsyncTask #1
  115 12-27 07:04:53.493  2145  2185 E AndroidRuntime: Process: it.niedermann.owncloud.notes, PID: 2145
  116 12-27 07:04:53.493  2145  2185 E AndroidRuntime: java.lang.RuntimeException: An error occurred while executing doInBackground()
  117 12-27 07:04:53.493  2145  2185 E AndroidRuntime:    at android.os.AsyncTask$4.done(AsyncTask.java:399)
  118 12-27 07:04:53.493  2145  2185 E AndroidRuntime:    at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
  119 12-27 07:04:53.493  2145  2185 E AndroidRuntime:    at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
  120 12-27 07:04:53.493  2145  2185 E AndroidRuntime:    at java.util.concurrent.FutureTask.run(FutureTask.java:271)
  121 12-27 07:04:53.493  2145  2185 E AndroidRuntime:    at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:289)
  122 12-27 07:04:53.493  2145  2185 E AndroidRuntime:    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
  123 12-27 07:04:53.493  2145  2185 E AndroidRuntime:    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
  124 12-27 07:04:53.493  2145  2185 E AndroidRuntime:    at java.lang.Thread.run(Thread.java:919)
  125 12-27 07:04:53.493  2145  2185 E AndroidRuntime: Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.length()' on a null object reference
  126 12-27 07:04:53.493  2145  2185 E AndroidRuntime:    at org.json.JSONTokener.nextCleanInternal(JSONTokener.java:121)
  127 12-27 07:04:53.493  2145  2185 E AndroidRuntime:    at org.json.JSONTokener.nextValue(JSONTokener.java:98)
  128 12-27 07:04:53.493  2145  2185 E AndroidRuntime:    at org.json.JSONArray.<init>(JSONArray.java:94)
  129 12-27 07:04:53.493  2145  2185 E AndroidRuntime:    at org.json.JSONArray.<init>(JSONArray.java:110)
  130 12-27 07:04:53.493  2145  2185 E AndroidRuntime:    at it.niedermann.owncloud.notes.util.ServerResponse$NotesResponse.getNotes(ServerResponse.java:37)
  131 12-27 07:04:53.493  2145  2185 E AndroidRuntime:    at it.niedermann.owncloud.notes.persistence.NoteServerSyncHelper$SyncTask.pullRemoteChanges(NoteServerSyncHelper.java:351)
  132 12-27 07:04:53.493  2145  2185 E AndroidRuntime:    at it.niedermann.owncloud.notes.persistence.NoteServerSyncHelper$SyncTask.doInBackground(NoteServerSyncHelper.java:277)
  133 12-27 07:04:53.493  2145  2185 E AndroidRuntime:    at it.niedermann.owncloud.notes.persistence.NoteServerSyncHelper$SyncTask.doInBackground(NoteServerSyncHelper.java:248)
  134 12-27 07:04:53.493  2145  2185 E AndroidRuntime:    at android.os.AsyncTask$3.call(AsyncTask.java:378)
  135 12-27 07:04:53.493  2145  2185 E AndroidRuntime:    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
  136 12-27 07:04:53.493  2145  2185 E AndroidRuntime:    ... 4 more
```

**Comment by stefan-niedermann** [comment]
So the notes app works fine until some point where you have to open the files app and authenticate it again? Are you using any other SSO app like News or Deck?

cc @tobiasKaminsky @david-development do you have similar problems with the news app?

**Comment by xxKeith20xx** [comment]
@stefan-niedermann yes, that's correct. I'm only using calendar/tasks but those are using caldav. I wonder if this is more of an issue with the NextCloud app? Also, I should mention I'm on Android 10.

**Comment by stefan-niedermann** [comment]
If you disable the authentication of the files app, so one can open it without finger print / pin, does everything work fine?

**Comment by xxKeith20xx** [comment]
Hmm, interestingly enough, no matter what setting I choose for the Nextcloud app it asks for me to authenticate. I'll dig into that side of things next, that seems suspect.

**Comment by David-Development** [comment]
Maybe there are some side effects when using sso so that the API is in a "locked" state until the user unlocks the files app. Maybe @tobiasKaminsky can throw in some thoughts? Does locking the files app means that the API is "locked", too?

**Comment by tobiasKaminsky** [comment]
> Does locking the files app means that the API is "locked", too?

Not that I am aware of, as this is "only" about UI. e.g. auto upload also works while the app is locked.

**Comment by stefan-niedermann** [comment]
@xxKeith20xx are you using F-Droid or Play Store (for both of the apps: Files & Notes)?

I noticed that the only people who are claiming that something doesn't work with SSO are getting their apps from F-Droid.

Maybe this is some issue with the signing-key or so?

**Comment by xxKeith20xx** [comment]
@stefan-niedermann I _am_ using the F-Droid versions for both Files and Notes.

**Comment by stefan-niedermann** [comment]
I just released v2.4.6 which comes with a new exception dialog. I hope that this will give us some better insights about what actually is happening.

If you want, you can directly install this zipped `.apk`-file for testing purposes.

[notes-2.4.6-(signed).apk.zip](https://github.com/stefan-niedermann/nextcloud-notes/files/4047941/notes-2.4.6-.signed.apk.zip)

**Comment by xxKeith20xx** [comment]
Got new info! After force-closing the Nextcloud app and opening notes, I get these errors after about 15-30 seconds:

```
Synchronization failed: do you have installed the files app?
```

Followed immediately by this:
```
com.nextcloud.android.sso.exceptions. NextcloudApiNotRespondingException: Nextcloud files app api is not responding. Please report this issue.
```

**Comment by xxKeith20xx** [comment]
Just tried 2.4.6 and it looks like it's working now :0

I uninstalled 2.4.4 and installed the 2.4.6 APK and then force closed the Nextcloud app and it looks good now.

**Comment by xxKeith20xx** [comment]
got that new exception error now:

```
```
App Version: 2.4.6
App Version Code: 69
Files App Version Code: 30090290

---

OS Version: 4.9.179-perf+(1912142009)
OS API Level: 29
Device: OnePlus6
Model (and Product): ONEPLUS A6003 (OnePlus6)

---

java.lang.RuntimeException: Unable to resume activity {it.niedermann.owncloud.notes/it.niedermann.owncloud.notes.android.activity.NotesListViewActivity}: java.lang.IllegalArgumentException: Service not registered: com.nextcloud.android.sso.api.AidlNetworkRequest$1@f2ef2a2
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4322)
	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4354)
	at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:52)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2109)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7682)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
Caused by: java.lang.IllegalArgumentException: Service not registered: com.nextcloud.android.sso.api.AidlNetworkRequest$1@f2ef2a2
	at android.app.LoadedApk.forgetServiceDispatcher(LoadedApk.java:1766)
	at android.app.ContextImpl.unbindService(ContextImpl.java:1810)
	at android.content.ContextWrapper.unbindService(ContextWrapper.java:741)
	at com.nextcloud.android.sso.api.AidlNetworkRequest.stop(AidlNetworkRequest.java:109)
	at com.nextcloud.android.sso.api.NextcloudAPI.stop(NextcloudAPI.java:80)
	at it.niedermann.owncloud.notes.persistence.NotesClient.updateAccount(NotesClient.java:99)
	at it.niedermann.owncloud.notes.persistence.NoteServerSyncHelper.updateAccount(NoteServerSyncHelper.java:141)
	at it.niedermann.owncloud.notes.android.activity.NotesListViewActivity.selectAccount(NotesListViewActivity.java:274)
	at it.niedermann.owncloud.notes.android.activity.NotesListViewActivity.onResume(NotesListViewActivity.java:228)
	at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1560)
	at android.app.Activity.performResume(Activity.java:7952)
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4312)
	... 11 more

```

**Comment by stefan-niedermann** [comment]
The [last stacktrace](https://github.com/stefan-niedermann/nextcloud-notes/issues/653#issuecomment-573378866) is not related and has been fixed with version `2.4.8`.

**Comment by stefan-niedermann** [comment]
@xxKeith20xx can you give us n update for this issue please? Does it still happen?

And: Because i didn't ask yet and the symptoms are identical: Are you using the **Ransomware Detection** App on your Nextcloud? ([It is known to block requests](https://github.com/undo-ransomware/ransomware_detection/issues/26).

**Comment by xxKeith20xx** [comment]
I am not using Ransomware Detection. I've been running the F-Droid versions of everything and it looks like I'm a bit behind due to the repos so I just switched to the play store versions. Was able to replicate by force-closing the Nextcloud app and then opening notes, but will give it some time to see if it really still persists!

**Comment by xxKeith20xx** [comment]
@stefan-niedermann unfortunately it seems to still exist - are you beginning to suspect it's something unique to my phone or nextcloud install?>

**Comment by stefan-niedermann** [comment]
Unfortunately yes. The files app in my environment is also locked, but the sync works, even if i didn't unlock the files app first.

Also noone else reported this issue yet, not from F-Droid neither from Play Store.

I will keep it open for some time, but if noone else is experiencing or able to reproduce this problem, i'm afraid that i cannot help you.

**Comment by zingmars** [comment]
I've been having the same issue, though I was hoping that this issue would solve it (which is why I didn't report it). Same problem - can't sync the notes app until I open and unlock the files app. It has been happening for a while now, and still happens with the latest version of the app from **f-droid**. My files app is from Google Play though.

Phone: Oneplus 6T with Android 10 (OxygenOS 10.3.0)
Nextcloud v17.0.3 (server hasn't been updated to v18 yet)
Apps:
Notes v.2.8.0 (f-droid)
Files v3.10.0 (g-play)

No ransomware detection (called ransomware recovery in the nextcloud store?). I do have an app called "Ransomware protection", but all it does is prevent uploading of files with certain extensions.

![image](https://user-images.githubusercontent.com/917126/73441094-1ca6cd80-435b-11ea-803f-56ba66144f46.png)

**Comment by stefan-niedermann** [comment]
Thank you, always upvote issue you have yourself, this shows me if other users are affected or not :)

@David-Development is experiencing the same issue in the News app which hints that the bug is in the SSO itself (see https://github.com/nextcloud/Android-SingleSignOn/issues/162).

Let's see what we can find there...

**Comment by zingmars** [comment]
Ah, looks like I forgot to do that when I subscribed to the thread.

Good to know that there's some progress being made.

**Comment by stefan-niedermann** [comment]
> no matter what setting I choose for the Nextcloud app it asks for me to authenticate

This is unclear to me. If you disanle the PIN in the files app, than the files app ahould never ask you for a PIN. Or did i get you wrong at this point?

I need to know if this issue is really directly connected to the PIN in the files app or if this also happens if the files app hasn't set amy PIN at all (@xxKeith20xx and @zingmars)

**Comment by zingmars** [comment]
I disabled PIN; force closed the NextCloud app and the issue still occurs.

**Comment by stefan-niedermann** [comment]
@zingmars since you confitmed, that the issue is **not** related to the PIN in the files app, i would like you to subscribe and upvote the following two issues:

- https://github.com/stefan-niedermann/nextcloud-notes/issues/710
- https://github.com/nextcloud/Android-SingleSignOn/issues/162

This way we can see how many people are actually affected by this issue and you will get notified as soon as we have a solution.

@xxKeith20xx can you please check whether or not this issue occurs for you **only** if you have an active PIN / Password protection in your files app.

It is important for us to keep your issue separate in this case. If you can reproduce the issue with **disabled** PIN / Password in your files app, please do the same: subscribe and upvote the two mentioned tickets and close this one.

Thank you for your help.

**Comment by xxKeith20xx** [comment]
@stefan-niedermann after switching to the google play release, I have not had an app passcode enabled. I do have 2FA enabled on the server.
